import json
import subprocess
import yaml
import copy

# Get existing deployment
cmd = [
    "kubectl",
    "get",
    "deployment",
    "chatapp-api",
    "-n",
    "chatapp",
    "-o",
    "json"
]

result = subprocess.check_output(cmd)
deployment = json.loads(result)

# -----------------------------
# Create GREEN deployment
# -----------------------------
green = copy.deepcopy(deployment)

green["metadata"]["name"] = "chatapp-api-green"

# Remove autogenerated metadata
for k in [
    "resourceVersion",
    "uid",
    "creationTimestamp",
    "generation",
    "managedFields"
]:
    green["metadata"].pop(k, None)

green.pop("status", None)

# Add slot=green labels
green["spec"]["selector"]["matchLabels"]["slot"] = "green"
green["spec"]["template"]["metadata"]["labels"]["slot"] = "green"

# Add environment variables
container = green["spec"]["template"]["spec"]["containers"][0]

container["env"] = [
    {
        "name": "SLOT",
        "value": "green"
    },
    {
        "name": "APP_NAME",
        "value": "Chat Backend API [green]"
    }
]

# -----------------------------
# Green service
# -----------------------------
green_service = {
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "name": "chatapp-api-green",
        "namespace": "chatapp"
    },
    "spec": {
        "selector": {
            "app.kubernetes.io/name": "chat-api",
            "app.kubernetes.io/instance": "chatapp",
            "slot": "green"
        },
        "ports": [{
            "port": 8000,
            "targetPort": 8000,
            "protocol": "TCP"
        }]
    }
}

# -----------------------------
# Blue service
# -----------------------------
blue_service = {
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "name": "chatapp-api-blue",
        "namespace": "chatapp"
    },
    "spec": {
        "selector": {
            "app.kubernetes.io/name": "chat-api",
            "app.kubernetes.io/instance": "chatapp",
            "slot": "blue"
        },
        "ports": [{
            "port": 8000,
            "targetPort": 8000,
            "protocol": "TCP"
        }]
    }
}

# Write YAML file
with open("bluegreen.yaml", "w") as f:
    yaml.dump_all(
        [blue_service, green, green_service],
        f,
        sort_keys=False
    )

print("Created bluegreen.yaml")

# Apply to Kubernetes
subprocess.run(["kubectl", "apply", "-f", "bluegreen.yaml"])
