services:

  api:
    build: .
    container_name: chat_api
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

    volumes:
      - .:/code

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy  
  

  db:
    image: mysql:8.0
    container_name: chat_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7
    container_name: chat_redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10  
      

volumes:
  mysql_data:
  redis_data: