apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "awschatapp.labels" . | nindent 4 }}

type: Opaque

stringData:
  SECRET_KEY: {{ .Values.api.secretKey | quote }}

  DB_PASSWORD: {{ .Values.db.password | quote }}

  {{- $dbBase := printf "mysql+pymysql://%s:%s@%s:%v/%s" .Values.db.username .Values.db.password .Values.db.host .Values.db.port .Values.db.name }}
  {{- if .Values.db.ssl.enabled }}
  DATABASE_URL: {{ printf "%s?ssl_ca=%s/%s" $dbBase .Values.db.ssl.mountPath .Values.db.ssl.certFile | quote }}
  {{- else }}
  DATABASE_URL: {{ $dbBase | quote }}
  {{- end }}

  {{- $scheme := ternary "rediss" "redis" .Values.redis.tls }}
  {{- if .Values.redis.authToken }}
  {{- $encodedToken := .Values.redis.authToken | urlquery }}
  REDIS_URL: {{ printf "%s://:%s@%s:%v" $scheme $encodedToken .Values.redis.host .Values.redis.port | quote }}
  {{- else }}
  REDIS_URL: {{ printf "%s://%s:%v" $scheme .Values.redis.host .Values.redis.port | quote }}
  {{- end }}
