{{- if .Values.api.serviceAccountName }}
# ServiceAccount is pre-created by Terraform (k8s.tf) and referenced here.
# This manifest only creates it when Terraform is not managing it.
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "awschatapp.fullname" . }}-sa
  labels:
    {{- include "awschatapp.labels" . | nindent 4 }}
{{- end }}
