apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: chatapp
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-http
      port: 4318
      targetPort: 4318
