apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
  namespace: chatapp
data:
  APP_NAME: "Chat Backend API"
  DEBUG: "False"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  CORS_ORIGINS: "http://localhost:3000"
  OTEL_SERVICE_NAME: "chat-api"
  OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
